The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) CCconfig         4) imkl/2020.1.217    7) libfabric/1.10.1
  2) gentoo/2020      5) intel/2020.1.217   8) openmpi/4.0.3
  3) gcccore/.9.3.0   6) ucx/1.8.0          9) StdEnv/2020
INFO:    underlay of /etc/localtime required more than 50 (68) bind mounts
/opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Missing logger folder: logs/lightning_logs
fix: yaml_path = /myDir/config/config_small.yaml
device = cpu
cuda device count = 0
fix: data_path = /myDir/data
fix: devices=1; accelerator=gpu
Traceback (most recent call last):
  File "/myDir/myTrain.py", line 132, in <module>
    main(config_path=yaml_path, config_name=config_name)
  File "/myDir/myTrain.py", line 88, in main
    trainer = pl.Trainer(
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 393, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 154, in __init__
    self._accelerator_flag = self._choose_gpu_accelerator_backend()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 371, in _choose_gpu_accelerator_backend
    raise MisconfigurationException("No supported gpu backend found!")
lightning_fabric.utilities.exceptions.MisconfigurationException: No supported gpu backend found!

# USER COMMENT: ok it actually does not detect gpu